Assets/Scenes/MatteScene.unity, Assets/Scripts/MathGameScripts/MathAnswerGeneratorScript.cs, UserSettings/Layouts/CurrentMaximizeLayout.dwlt
You can now select the correct answer. If you do, a new math question will be generated
=> #4.6 välja rätt svar

Assets/Scenes/MatteScene.unity, Assets/Scripts/MathGameScripts/MathAnswerGeneratorScript.cs, Assets/Scripts/MathGameScripts/MathQuestionGenerator.cs
When wrong answer is selected the box now becomes red. It will become blue again when a correct answer is given instead
=> #4.7 välja fel svar

Assets/Scenes/MusicGame.unity, Assets/Scripts/MusicGame/DragAndDropNote.cs, UserSettings/EditorUserSettings.asset
Added vertical snap points and implemented "snap to closest" functionallity for notes.
=> #6.3 olika tonhojder

Assets/Scenes/WeatherScene.unity, Assets/Scripts/WeatherScripts/RequestPermissionScript.cs, Assets/Scripts/WeatherScripts/RequestPermissionScript.cs.meta
App now asks for permission to find location when going into the weather game on android devices
=> Location permission

Assets/Scenes/MusicGame.unity, Assets/Scripts/MusicGame/DragAndDropNote.cs, Assets/Scripts/MusicGame/MusicGameScripts.asmdef, Assets/Scripts/MusicGame/MusicGameScripts.asmdef.meta
Now the note object plays different notes depending on pitch and instrument.
=> #6.5 koppla ton till tonhojd

Assets/AstarPathfindingProject/Behaviors/AIDestinationSetter.cs, Assets/Scenes/MatteScene.unity, Assets/Scripts/MathGameScripts/MathAnswerGeneratorScript.cs, Assets/Scripts/MathGameScripts/ScreenTransition.cs, Assets/Scripts/MathGameScripts/TriggerScreenTransition.cs
Have added a fade when a new math excercise is shown. The player will move upp and stop for 0.2 seconds and then the fade will execute.
=> #4.9 fade animation för svar

Assets/Scripts/MemoryGameScripts/MemoryController.cs
=> Memory: Ljud vid klick

Assets/AstarPathfindingProject/Behaviors/AIDestinationSetter.cs, Assets/Scenes/MatteScene.unity, Assets/Scripts/MathGameScripts/PlayerAnimatorController.cs, Assets/Scripts/MathGameScripts/PlayerAnimatorController.cs.meta, Assets/Scripts/MathGameScripts/WrongWayControllerScript.cs
The player now animates as it goes around in the math game
=> #4.11 animera karaktären

Assets/Scenes/WeatherScene.unity, Assets/Scripts/WeatherScripts/DragAndDropClothing.cs, Assets/WeatherGame/Clothes/Sun/sandaler.png.meta, Assets/WeatherGame/Clothes/Sun/t-shirt white.png.meta, Assets/WeatherGame/Clothes/Wind/långbyxor.png.meta, UserSettings/EditorUserSettings.asset
Lade till mer kläder och fixade knappar för alla klädestyper igen.
=> Userstory #3.14 lägg till resterande kläder

Assets/Scenes/Temp3.unity, Assets/Scripts/MainMenuScripts/MainMenuController.cs, Assets/Scripts/MainMenuScripts/Navigate.cs, Assets/Scripts/MainMenuScripts/PortalCollision.cs, Assets/Scripts/MainMenuScripts/PortalCollision.cs.meta, Assets/Scripts/MainMenuScripts/PortalHandler.cs, Assets/Scripts/MainMenuScripts/StorePortal.cs, Assets/Scripts/MainMenuScripts/StorePortal.cs.meta, ProjectSettings/EditorBuildSettings.asset
Must change in MainMenuController's OnGoBackButtonClick to be able test the functionality of the character returning out of the portal it came from.
=> #1.5 fungerande portaler

ProjectSettings/EditorBuildSettings.asset, ProjectSettings/ProjectSettings.asset
Changed the name of the application. Tested this and it works on android, still needs to be tested on IOS. But it looks like it will work there too since it was one simple settings change
=> UserStory #8.4 Changed application name

Assets/Materials.meta, Assets/Materials/LineMaterial.mat, Assets/Materials/LineMaterial.mat.meta, Assets/Scenes/LearnWords.unity, Assets/Scripts/LearnWordsGameScripts/ImageController.cs, Assets/Scripts/LearnWordsGameScripts/LearnWordsGameHandler.cs, Assets/Scripts/LearnWordsGameScripts/LetterController.cs
The memorygame now drawes a line between the chosen cards.
=> Userstory #5.10 Göra streck mellan val

Assets/Prefabs/MusicPrefabs/PianoNote.prefab, Assets/Prefabs/MusicPrefabs/TrumpetNote.prefab, Assets/Prefabs/MusicPrefabs/UkeleleNote.prefab, Assets/Scenes/MusicGame.unity, Assets/Scripts/MusicGame/DragAndDropNote.cs
Added icons for all notes that you drag out from the pools
=> #6.10 Ändra bild på noter

Assets/Scenes/LearnWords.unity, Assets/Scripts/LearnWordsGameScripts/ImageController.cs, Assets/Scripts/LearnWordsGameScripts/LearnWordsGameHandler.cs, Assets/Scripts/LearnWordsGameScripts/LetterController.cs
I have reworked the code behind the word game to not validate answers in real time but instead when you press a "Check answers" button. This means that you can reselect answers before you hit the button. I have also changed how the cards are colored to better match the new game idea. 
When you are selecting a card it is yellow, then when you check your answers all right combinations will turn green. Unchecked cards will remain thier normal color.
=> #word game rework

Assets/Scenes/MatteScene.unity
The fox is now visible when selecting a wrong answer moving up / down
=> The fox is visible now

Assets/Prefabs/MusicPrefabs/TrumpetNote.prefab, Assets/Scripts/MusicGame/DragAndDropNote.cs
Now the notes can't be placed on top of eachother
=> #6.19 fixa bugg med flera noter på samma plats

Assets/Scenes/MusicGame.unity, Assets/Scripts/MainMenuScripts/Navigate.cs, Assets/Scripts/MusicGame/MarkerMover.cs, Assets/Scripts/MusicGame/PlayMusic.cs
Moved the starting position of the fox to the left. Now when the first jump ends the first beat starts to play.
Also works with looping. When looping the fox jumps from the last beat to the first beat and skips the starting position.
=> #6.20 placering av räven

Assets/Scenes/LearnWords.unity, Assets/Scripts/LearnWordsGameScripts/DragLineScript.cs, Assets/Scripts/LearnWordsGameScripts/DragLineScript.cs.meta, Assets/Scripts/LearnWordsGameScripts/LearnWordsGameHandler.cs, Assets/Scripts/LearnWordsGameScripts/LetterController.cs
You can now drag (not just klick) the line between two differen cards in the word game. Ther should not be any bug as long as you are in the check answer directly mode but that is what the stakeholder wanted.
=> #5.12 kunna dra linje

Assets/Resources/Animal_sounds/Edited_Sounds/Eagle.wav.meta, Assets/Scenes/MemoryGame.unity
Är osäker på om djurljuden bör balanseras också?
=> Har balanserat victory och rightanswer ljud

Assets/Scenes/MemoryGame.unity, Assets/Scripts/MemoryGameScripts/FlipCard.cs
Animation is now not frame rate based. Also made endingscreen not draged out to the side
=> #2.17 fixa vändingsanimation

Assets/Scenes/LearnWords.unity, Assets/Scripts/LearnWordsGameScripts/RandomBirdFlyingScript.cs, Assets/Scripts/LearnWordsGameScripts/RandomBirdFlyingScript.cs.meta
There now exist a script that moves the flying birds randomly in the void in the word game
=> Random bird movement

Assets/Scenes/MusicGame.unity, Assets/Scripts/MusicGame/PlayMusic.cs
Added the ability to loop at the end of the first row if the second row is empty.
The feature can also end music playing early if the second row of notes is empty.
=> #6.21 loopa tidigt

Assets/Scenes/WeatherScene.unity, Assets/Scripts/WeatherScripts/ValidateClothes.cs, Assets/Scripts/WeatherScripts/speechBubble.cs
Added a speechbubble with sound for when the player has choosen the correct clothes
=> Added a speech bubble for correct clothes

Assets/Scenes/WeatherScene.unity
Fleece now counts as a shirt instead of a jacket
=> Userstory #3.35 fleece räknas som t shirt

Assets/Scenes/MusicGame.unity
I changed color of two buttons. (Why was this velocity 3?)
=> Changed color

Assets/Scenes/MusicGame.unity
Added backround to the instrument pool.
=> #6.25 bakrund till pooler

Assets/Scenes/MemoryGame.unity
=> Fix added music to memory game again

Assets/Scenes/WeatherScene.unity, Assets/Scripts/WeatherScripts/ValidateClothes.cs
Added a button in the top right that can be used for taking all the clothes off the character.
=> Userstory #3.31 Lättare att ta bort alla klädesplagg på karaktären

Assets/Scenes/MemoryGame.unity, Assets/Scripts/MemoryGameScripts/MemoryController.cs
I have fixed all sound bugs in the memory game. It can now only play sound from the card you have selected.
=> #2.21 bugg med ljud

Assets/Sunnyland/artwork/Environment/tileset-sliced.png.meta, Assets/Tiny RPG Forest/Artwork/Environment/tileset-sliced.png.meta
I think I have fixed the blue line bug with this simple fix as I can not see them any more. This will have to be tested more but I think this will work.
Do NOT accept this into main branch before it is fixed (It will then only cause more problems). This is created from a old branch that is not broken
=> #8.08 Blue line bug

Assets/Scenes/MatteScene.unity, Assets/Scripts/MathGameScripts/MathQuestionGenerator.cs
Removed generate button in mathgame.
Also removed the answer in the question
=> Userstory #4.16 Ta bort generera uppgift knapp

Assets/Scripts/WeatherScripts/ThermometerControl.cs
=> changed from ? to °

Assets/Scenes/LearnWords.unity
I removed developer buttons in the word game
=> Dissabled the dev buttons so they are not in use

Assets/Scripts/MusicGame/DragAndDropNote.cs, ProjectSettings/ProjectSettings.asset
Now the notes can snap back to their previously snapped position.
When doing this it also plays the notes' sound.
Also added the main fox to the splashscreen
=> Allowed notes to snap back to placed position

Assets/Images/MathGame/HouseIcon.png.meta, Assets/Prefabs/GoBackButtonImage.prefab, Assets/Scenes/WeatherScene.unity, Assets/Scripts/WeatherScripts/ThermometerControl.cs, Assets/Scripts/WeatherScripts/ValidateClothes.cs
I have changed the house sprite in the weather game / go back button to not have any transparency at the edges. This fixes a issue where button was clickable outside the button.
I have resaved the files as UTF-8 files wich I hope will fix the font issues (looks good in github now at least). This remains to be tested on actuall device later!
I then fixed an issue where the speach bubble was rendered under the player clothing by changing render priority / layer.
I also moved the "remove clothes" button to be under the darkend area when a menu comes up so that you can not click it any more.
Last I made the weather sound louder so you can hear them better when you play.
=> #8.10 fixing fonts

README.md
Wrote a new readMe file
Only thing missing is a drive link that I can't get
=> Userstory #0.07 readme

Assets/Scenes/LearnWords.unity, Assets/Scripts/LearnWordsGameScripts/WinningSound.cs
Added new sound effect in word game.
When the player matches all the cards, the "Wow, bra jobbat!" sound will now be played
=> New audio effect

Assets/Scenes/MainMenu.unity, Assets/Scenes/WeatherScene.unity, Assets/Scripts/WeatherScripts/DragAndDropClothing.cs, Assets/Scripts/WeatherScripts/StartMeunu.cs
I have done everything the commits say I have done.
The removal of clothing movement is only when you have a menu open. If you can not place a clothing item when there are not any menus on screen, that is a bug so please say if you find something like this..
=> Small fixes in weather game

Assets/Scenes/MemoryGame.unity, Assets/Scenes/WeatherScene.unity, ProjectSettings/ProjectSettings.asset
Changed color of ending font in memory game to match all other font color and small thing i weather game
=> Last changes before demo
